language: ruby
rvm:
- 2.3.4

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./script/cibuild

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master

env:
  - global:
  NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - ENCRYPTION_LABEL: c68fb307f099
  - COMMIT_AUTHOR_EMAIL: "ramakrishnan.rkology@gmail.com"
  # Please add the following to your build script (before_install stage in your .travis.yml, for instance):
  #  openssl aes-256-cbc -K $encrypted_c68fb307f099_key -iv $encrypted_c68fb307f099_iv -in merakipost.enc -out merakipost -d
  # Pro Tip: You can add it automatically by running with --add.

sudo: false # route your build to the container-based infrastructure for a faster build
