# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
paginate: 5
language: 'en-in'
timezone: Asia/Kolkata
future: false

# Website info
name: 'Meraki Post'
description: "All about books, book reviews, adaptations to movies, book hauls, authors and a lot more about books."

# Author's info
authors:
  ram:
    name: ram
    displayname: Ram Iyer
    bio: Writer, PowerShell freak, philophobe, dreamer, and a typographer.
    url: https://ramiyer.me
    image: assets/images/ram.png
    facebook: theramiyer
    twitter: theramiyer
    shorturl: ramiyer.me
    location: 'Bangalore, KA'

  veena:
    name: veena
    displayname: Veena Choudhary
    bio: An avid reader and history fanatic.
    twitter: veena___singh
    facebook: ar.veena.5
    image: assets/images/veena.png
    location: 'Mumbai, MH'
    url: https://www.merakipost.com
    shorturl: merakipost.com

author: 'Veena Choudhary'
# edit 'categories' in the front matter of every post to match this username
nickname: veena
bio: An avid reader and history fanatic.
image: assets/images/veena.png

# social links
facebook: merakipost
twitter: merakipost

url: 'http://test.merakipost.com'
shorturl: 'test.merakipost.com'
google_analytics:
disqus: username
baseurl: /
tagpage: /tags/
categorypage: '/categories/'

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude: [vendor]

# Turn on smart quotes
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      logo: 'assets/images/merakipost.svg'
      cover: 'assets/images/cover1.jpg'
      subclass: 'post tag-test tag-content'
      navigation: True
      author: veena
