# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
paginate: 5
language: 'en-in'
timezone: Asia/Kolkata
future: false

# Website info
name: 'Typo Demo'
description: "Everything tech from LOGO to Azure Cloud. But patience and baby steps, first. (Also, we’re still under construction.)"

# Author's info
authors:
  ram:
    displayname: Ram Iyer
    bio: Writer, PowerShell freak, philophobe, dreamer, and a typographer.
    url: https://ramiyer.me
    image: assets/images/ram.png
    facebook: theramiyer
    twitter: theramiyer
    shorturl: ramiyer.me
    location: 'Bangalore, KA'

  veena:
    displayname: Veena Choudhary
    bio: Reader, blogger, dreamer.
    twitter: veena___singh
    image: assets/images/veena.png
    location: 'Mumbai, MH'

author: 'Ram Iyer'
# edit 'categories' in the front matter of every post to match this username
nickname: ram
bio: 'Writer, PowerShell freak, philophobe, dreamer, and a typographer.'
image: 'assets/images/ram.png'

# social links
facebook: theramiyer
twitter: theramiyer

url: 'http://typo.midnightlamp.black'
short_url: 'typo.midnightlamp.black'
google_analytics: UA-96215433-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Turn on smart quotes
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      logo: 'assets/images/ghost.png'
      cover: 'assets/images/cover2.jpg'
      subclass: 'post tag-test tag-content'
      navigation: True

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: crimsoncanines
repo: typo
branch: master
relative_source: ../typo.midnightlamp.black/
destination: ../jasper-pages/
production_url:  https://crimsoncanines.github.io/typo/
source_url:      https://github.com/crimsoncanines/typo

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
