# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
paginate: 6
language: 'en-in'
timezone: Asia/Kolkata
future: false

# Website info
name: 'Meraki Post'
description: "All about books, book reviews, adaptations to movies, book hauls, authors and a lot more about books."

# Author's info
authors:
  veena:
    name: veena
    displayname: Veena Choudhary
    bio: An avid reader and history fanatic.
    url: https://www.merakipost.com
    image: assets/images/veena.png
    facebook: ar.veena.5
    twitter: veena___singh
    shorturl: merakipost.com
    location: 'Mumbai, MH'

  ram:
    name: ram
    displayname: Ram Iyer
    bio: Writer, PowerShell freak, philophobe, dreamer, and a typographer.
    url: https://ramiyer.me
    image: assets/images/ram.png
    facebook: theramiyer
    twitter: theramiyer
    shorturl: ramiyer.me
    location: 'Bangalore, KA'

  gazala:
    name: gazala
    displayname: Gazala Amreen
    bio: Logophile, bibliophile, writer, designer, high on wanderlust and all things pretty
    twitter: gazl_jot
    facebook: archgazl
    image: assets/images/gazala.png
    location: Bangalore, KA
    url: https://www.merakipost.com
    shorturl: merakipost.com

  pooja:
    name: pooja
    displayname: Pooja Ram
    bio:
    twitter: poojak8
    facebook: poojaram08
    image: assets/images/pooja.png
    location: Bangalore, KA
    url: https://www.merakipost.com
    shorturl: merakipost.com

# social links
facebook: merakipost
twitter: merakipost

url: 'http://www.merakipost.com'
shorturl: 'www.merakipost.com'
google_analytics: 97200314
disqus: username
baseurl: /
tagpage: /tags/
categorypage: /categories/

# Permalinks
permalink: /:year/:month/:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude: [vendor]

# Turn on smart quotes
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  syntax_highlighter: rouge
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      logo: 'assets/images/merakipost.svg'
      cover: 'assets/images/cover1.jpg'
      subclass: 'post tag-test tag-content'
      navigation: True
      author: veena
